version: '3'
services:
  nginx:
    image: nginx:1.15
    ports:
      - "80:80"
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql:/var/lib/mysql
  hello-world:
    image: hello-world:linux
    depends_on:
      - mysql
      - nginx
volumes:
  mysql:
